### ISSUE TITLE
Add support for subclasses of JsonObject

### ISSUE THREAD

**Issue by nicolaiwadstrom** [eclipse-vertx/vertx-codegen#172]
It would make a lot of sense to add support for identification of subclasses of JsonObject to be treated as it where a JsonObject, to be used with Service Proxies etc.

We have a larger java based project that has been migrated over to Vert.x over time, it has a lot of domain model objects that are using JsonObject as it's backing (recently refactored it to subclass JsonObject). 

It is preferable for our use case and many others to have a model object with coded getters/setters for the domain model and associated helper methods (we are doing MD5 hashing and other things for example), but backed by the flexibility of the schema-less structure of JsonObject - especially for Service Proxies.

The current implementation just checks if the class name equals JsonObject (or JsonArray), instead of checking if it is an assignable subclass of it.

**Comment by vietj** [comment]
@nicolaiwadstrom why don't you use Vert.x data objects that extends JsonObject ? these are recognized as JsonObject by the code generation and it would be easy to handle

**Comment by nicolaiwadstrom** [comment]
Tried that, but the pre-processing when you do that try to interpret the set/get methods on the object and generates a build error (aborts build) if they contains types not supported (even though the get/set method code manages the transformation into the underlying JsonObject).

In other words, that approach breaks for 50 % of the more complex model objects (and the reason we built subclassing with JsonObject backing) is to avoid conversion boilerplate code repeated across the code base.

Just treating any JsonObject/JsonArray or subclass thereof JsonObject/JsonArray would work for all the use cases...

**Comment by vietj** [comment]
@nicolaiwadstrom are you certain of that ? the codegen processor when it does not know a type just ignores it according to the tests. can you provide an example ?

**Comment by nicolaiwadstrom** [comment]
The error message complains about the data types, but let me do another test to verify this to be sure (might be error message is the issue, and there is another issue...).

**Comment by vietj** [comment]
@nicolaiwadstrom thanks
