### ISSUE TITLE
Improve project modularisation

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-codegen#358]
The project structure is a single jar file that contains everything all classes.

With the addition of protobuf generation we have added a new module to the project which create potential split package issues that we should avoid.

We should think about making it more modular by breaking it in more modules (annotations, processor, json generator).

- vertx-codegen-processor : io.vertx.codegen.processor
- vertx-codegen-annotations : io.vertx.codegen.annotations
- vertx-codegen-json : io.vertx.codegen.json.
- vertx-codegen-protobuf : io.vertx.codegen.protobuf

The `vertx-codegen` module would become like an uber jar of that for backward compatibility. Code would be repackaged accordingly and the `vertx-codegen` module would contain a `io.vertx.codegen.CodegenProcessor` class inheriting from the repackaged processor class for backward compatibility.

**Comment by vietj** [comment]
see https://github.com/eclipse-vertx/vertx-codegen/pull/362

**Comment by cvgaviao** [comment]
@vietj , what do you think about splitting the processor project into two? One for @DataObject and the other for @VertxGen. Also, create one module just for the annotations.

This way would be easier to have a new processor project using JDK 16 for the #340, which would reuse the annotations and data_objects project.
