### ISSUE TITLE
Canonical protobuf json format support

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-codegen#360]
The json protobuf format is optimised for vertx JSON types (e.g it can a an integer type) to get more compact json representations. We should also support this format https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/struct.proto and be wire compatible with it (which means using the same tags), so our messages can be compatible with `com.google.protobuf.Struct`

That would be declared on the `@Protobuf` annotation, e.g `@Protobuf(compactJson=false)`

**Comment by lwlee2608** [comment]
I will be working on this.
